/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/AdminDashboard': RouteRecordInfo<
      '/AdminDashboard',
      '/AdminDashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Bookings': RouteRecordInfo<
      '/Bookings',
      '/Bookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BrowseRooms': RouteRecordInfo<
      '/BrowseRooms',
      '/BrowseRooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ErrorNotFound': RouteRecordInfo<
      '/ErrorNotFound',
      '/ErrorNotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/LoginPage': RouteRecordInfo<
      '/LoginPage',
      '/LoginPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ManageResources': RouteRecordInfo<
      '/ManageResources',
      '/ManageResources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MyBookings': RouteRecordInfo<
      '/MyBookings',
      '/MyBookings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/PricingRules': RouteRecordInfo<
      '/PricingRules',
      '/PricingRules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Profile': RouteRecordInfo<
      '/Profile',
      '/Profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Register': RouteRecordInfo<
      '/Register',
      '/Register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Reports': RouteRecordInfo<
      '/Reports',
      '/Reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Resources': RouteRecordInfo<
      '/Resources',
      '/Resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ResourceTypes': RouteRecordInfo<
      '/ResourceTypes',
      '/ResourceTypes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Settings': RouteRecordInfo<
      '/Settings',
      '/Settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/UserDashboardPage': RouteRecordInfo<
      '/UserDashboardPage',
      '/UserDashboardPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/AdminDashboard.vue': {
      routes:
        | '/AdminDashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Bookings.vue': {
      routes:
        | '/Bookings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BrowseRooms.vue': {
      routes:
        | '/BrowseRooms'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ErrorNotFound.vue': {
      routes:
        | '/ErrorNotFound'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/LoginPage.vue': {
      routes:
        | '/LoginPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ManageResources.vue': {
      routes:
        | '/ManageResources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/MyBookings.vue': {
      routes:
        | '/MyBookings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/PricingRules.vue': {
      routes:
        | '/PricingRules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Profile.vue': {
      routes:
        | '/Profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Register.vue': {
      routes:
        | '/Register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Reports.vue': {
      routes:
        | '/Reports'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Resources.vue': {
      routes:
        | '/Resources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ResourceTypes.vue': {
      routes:
        | '/ResourceTypes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Settings.vue': {
      routes:
        | '/Settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/UserDashboardPage.vue': {
      routes:
        | '/UserDashboardPage'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
